export const quizQuestions = [
  {
    level: "Easy",
    soal: "Apa ibu kota Indonesia?",
    pilihan: ["Surabaya", "Jakarta", "Bandung", "Medan"],
    jawaban: "Jakarta",
  },
  {
    level: "Easy",
    soal: "Hewan apa yang dikenal sebagai 'Raja Hutan'?",
    pilihan: ["Harimau", "Singa", "Serigala", "Beruang"],
    jawaban: "Singa",
  },
  {
    level: "Easy",
    soal: "Mata uang resmi Jepang adalah?",
    pilihan: ["Won", "Yen", "Peso", "Ringgit"],
    jawaban: "Yen",
  },
  {
    level: "Easy",
    soal: "Benua terbesar di dunia adalah?",
    pilihan: ["Amerika", "Asia", "Afrika", "Eropa"],
    jawaban: "Asia",
  },
  {
    level: "Easy",
    soal: "Siapa penemu lampu pijar?",
    pilihan: ["Nikola Tesla", "Albert Einstein", "Thomas Edison", "Isaac Newton"],
    jawaban: "Thomas Edison",
  },
  {
    level: "Easy",
    soal: "Manusia bernafas dengan menggunakan?",
    pilihan: ["Paru-paru", "Hati", "Lambung", "Ginjal"],
    jawaban: "Paru-paru",
  },
  {
    level: "Easy",
    soal: "Planet terdekat dengan Matahari adalah?",
    pilihan: ["Bumi", "Mars", "Venus", "Merkurius"],
    jawaban: "Merkurius",
  },
  {
    level: "Easy",
    soal: "Berapa jumlah huruf dalam abjad alfabet Indonesia?",
    pilihan: ["24", "28", "26", "30"],
    jawaban: "26",
  },
  {
    level: "Easy",
    soal: "Warna dasar bendera Indonesia adalah?",
    pilihan: ["Biru dan Putih", "Merah dan Putih", "Hijau dan Putih", "Kuning dan Hitam"],
    jawaban: "Merah dan Putih",
  },
  {
    level: "Easy",
    soal: "Hewan apa yang mampu hidup di dua alam?",
    pilihan: ["Mamalia", "Serangga", "Amfibi", "Reptil"],
    jawaban: "Amfibi",
  },
  {
    level: "Medium",
    soal: "Gunung tertinggi di dunia adalah?",
    pilihan: ["Kilimanjaro", "Everest", "Elbrus", "Denali"],
    jawaban: "Everest",
  },
  {
    level: "Medium",
    soal: "Siapa presiden pertama Indonesia?",
    pilihan: ["Soeharto", "Soekarno", "BJ Habibie", "Megawati"],
    jawaban: "Soekarno",
  },
  {
    level: "Medium",
    soal: "Lapisan atmosfer yang melindungi bumi dari radiasi ultraviolet adalah?",
    pilihan: ["Troposfer", "Stratosfer", "Ozon", "Mesosfer"],
    jawaban: "Ozon",
  },
  {
    level: "Medium",
    soal: "Bintang terdekat dari Bumi selain Matahari adalah?",
    pilihan: ["Proxima Centauri", "Sirius", "Betelgeuse", "Vega"],
    jawaban: "Proxima Centauri",
  },
  {
    level: "Medium",
    soal: "Laut terbesar di dunia adalah?",
    pilihan: ["Samudra Pasifik", "Samudra Atlantik", "Laut Mediterania", "Samudra Hindia"],
    jawaban: "Samudra Pasifik",
  },
  {
    level: "Medium",
    soal: "Berapa jumlah provinsi di Indonesia saat ini?",
    pilihan: ["33", "38", "34", "40"],
    jawaban: "38",
  },
  {
    level: "Medium",
    soal: "Burung yang tidak bisa terbang adalah?",
    pilihan: ["Merpati", "Elang", "Jalak", "Penguin"],
    jawaban: "Penguin",
  },
  {
    level: "Medium",
    soal: "Unsur paling melimpah di kerak bumi adalah?",
    pilihan: ["Oksigen", "Karbon", "Hidrogen", "Nitrogen"],
    jawaban: "Oksigen",
  },
  {
    level: "Medium",
    soal: "Penulis novel 'Laskar Pelangi' adalah?",
    pilihan: ["Tere Liye", "Andrea Hirata", "Pramoedya Ananta Toer", "Habiburrahman El Shirazy"],
    jawaban: "Andrea Hirata",
  },
  {
    level: "Medium",
    soal: "Simbol kimia untuk emas adalah?",
    pilihan: ["Ag", "Au", "Fe", "Hg"],
    jawaban: "Au",
  },
  {
    level: "Medium",
    soal: "Tahun berapakah Indonesia merdeka?",
    pilihan: ["1940", "1945", "1950", "1935"],
    jawaban: "1945",
  },
  {
    level: "Medium",
    soal: "Organ terbesar dalam tubuh manusia adalah?",
    pilihan: ["Jantung", "Paru-paru", "Otak", "Kulit"],
    jawaban: "Kulit",
  },
  {
    level: "Medium",
    soal: "Hewan yang dikenal dengan sebutan 'hewan paling lambat' adalah?",
    pilihan: ["Siput", "Kura-kura", "Lintah", "Sloth"],
    jawaban: "Sloth",
  },
  {
    level: "Medium",
    soal: "Mata uang resmi Thailand adalah?",
    pilihan: ["Peso", "Baht", "Ringgit", "Rupiah"],
    jawaban: "Baht",
  },
  {
    level: "Medium",
    soal: "Di mana letak Menara Eiffel?",
    pilihan: ["Italia", "Prancis", "Spanyol", "Jerman"],
    jawaban: "Prancis",
  },
  {
    level: "Medium",
    soal: "Dalam sistem kalender Masehi, bulan apa yang memiliki 28 atau 29 hari?",
    pilihan: ["Januari", "Maret", "Februari", "April"],
    jawaban: "Februari",
  },
  {
    level: "Medium",
    soal: "Apa yang digunakan lebah untuk membuat madu?",
    pilihan: ["Nektar", "Serbuk sari", "Getah pohon", "Embun"],
    jawaban: "Nektar",
  },
  {
    level: "Medium",
    soal: "Sungai terpanjang di dunia adalah?",
    pilihan: ["Sungai Nil", "Sungai Amazon", "Sungai Mississippi", "Sungai Yangtze"],
    jawaban: "Sungai Nil",
  },
  {
    level: "Medium",
    soal: "Alat musik tradisional dari Bali adalah?",
    pilihan: ["Angklung", "Gamelan", "Sasando", "Kolintang"],
    jawaban: "Gamelan",
  },
  {
    level: "Medium",
    soal: "Hewan mamalia yang bisa terbang adalah?",
    pilihan: ["Burung Hantu", "Kelelawar", "Elang", "Merpati"],
    jawaban: "Kelelawar",
  },
];
