export const quizQuestions = [
  {
    level: "Easy",
    soal: "Apa ibu kota Indonesia?",
    pilihan: ["Surabaya", "Jakarta", "Bandung", "Medan"],
    jawaban: "Jakarta",
  },
  {
    level: "Easy",
    soal: "Hewan apa yang dikenal sebagai 'Raja Hutan'?",
    pilihan: ["Harimau", "Singa", "Serigala", "Beruang"],
    jawaban: "Singa",
  },
  {
    level: "Easy",
    soal: "Mata uang resmi Jepang adalah?",
    pilihan: ["Won", "Yen", "Peso", "Ringgit"],
    jawaban: "Yen",
  },
  {
    level: "Easy",
    soal: "Benua terbesar di dunia adalah?",
    pilihan: ["Amerika", "Asia", "Afrika", "Eropa"],
    jawaban: "Asia",
  },
  {
    level: "Easy",
    soal: "Siapa penemu lampu pijar?",
    pilihan: ["Nikola Tesla", "Albert Einstein", "Thomas Edison", "Isaac Newton"],
    jawaban: "Thomas Edison",
  },
  {
    level: "Easy",
    soal: "Manusia bernafas dengan menggunakan?",
    pilihan: ["Paru-paru", "Hati", "Lambung", "Ginjal"],
    jawaban: "Paru-paru",
  },
  {
    level: "Easy",
    soal: "Planet terdekat dengan Matahari adalah?",
    pilihan: ["Bumi", "Mars", "Venus", "Merkurius"],
    jawaban: "Merkurius",
  },
  {
    level: "Easy",
    soal: "Berapa jumlah huruf dalam abjad alfabet Indonesia?",
    pilihan: ["24", "28", "26", "30"],
    jawaban: "26",
  },
  {
    level: "Easy",
    soal: "Warna dasar bendera Indonesia adalah?",
    pilihan: ["Biru dan Putih", "Merah dan Putih", "Hijau dan Putih", "Kuning dan Hitam"],
    jawaban: "Merah dan Putih",
  },
  {
    level: "Easy",
    soal: "Hewan apa yang mampu hidup di dua alam?",
    pilihan: ["Mamalia", "Serangga", "Amfibi", "Reptil"],
    jawaban: "Amfibi",
  },
  {
    level: "Medium",
    soal: "Gunung tertinggi di dunia adalah?",
    pilihan: ["Kilimanjaro", "Everest", "Elbrus", "Denali"],
    jawaban: "Everest",
  },
  {
    level: "Medium",
    soal: "Siapa presiden pertama Indonesia?",
    pilihan: ["Soeharto", "Soekarno", "BJ Habibie", "Megawati"],
    jawaban: "Soekarno",
  },
  {
    level: "Medium",
    soal: "Lapisan atmosfer yang melindungi bumi dari radiasi ultraviolet adalah?",
    pilihan: ["Troposfer", "Stratosfer", "Ozon", "Mesosfer"],
    jawaban: "Ozon",
  },
  {
    level: "Medium",
    soal: "Bintang terdekat dari Bumi selain Matahari adalah?",
    pilihan: ["Proxima Centauri", "Sirius", "Betelgeuse", "Vega"],
    jawaban: "Proxima Centauri",
  },
  {
    level: "Medium",
    soal: "Laut terbesar di dunia adalah?",
    pilihan: ["Samudra Pasifik", "Samudra Atlantik", "Laut Mediterania", "Samudra Hindia"],
    jawaban: "Samudra Pasifik",
  },
  {
    level: "Medium",
    soal: "Berapa jumlah provinsi di Indonesia saat ini?",
    pilihan: ["33", "38", "34", "40"],
    jawaban: "38",
  },
  {
    level: "Medium",
    soal: "Burung yang tidak bisa terbang adalah?",
    pilihan: ["Merpati", "Elang", "Jalak", "Penguin"],
    jawaban: "Penguin",
  },
  {
    level: "Medium",
    soal: "Unsur paling melimpah di kerak bumi adalah?",
    pilihan: ["Oksigen", "Karbon", "Hidrogen", "Nitrogen"],
    jawaban: "Oksigen",
  },
  {
    level: "Medium",
    soal: "Penulis novel 'Laskar Pelangi' adalah?",
    pilihan: ["Tere Liye", "Andrea Hirata", "Pramoedya Ananta Toer", "Habiburrahman El Shirazy"],
    jawaban: "Andrea Hirata",
  },
  {
    level: "Medium",
    soal: "Simbol kimia untuk emas adalah?",
    pilihan: ["Ag", "Au", "Fe", "Hg"],
    jawaban: "Au",
  },
  {
    level: "Medium",
    soal: "Tahun berapakah Indonesia merdeka?",
    pilihan: ["1940", "1945", "1950", "1935"],
    jawaban: "1945",
  },
  {
    level: "Medium",
    soal: "Organ terbesar dalam tubuh manusia adalah?",
    pilihan: ["Jantung", "Paru-paru", "Otak", "Kulit"],
    jawaban: "Kulit",
  },
  {
    level: "Medium",
    soal: "Hewan yang dikenal dengan sebutan 'hewan paling lambat' adalah?",
    pilihan: ["Siput", "Kura-kura", "Lintah", "Sloth"],
    jawaban: "Sloth",
  },
  {
    level: "Medium",
    soal: "Mata uang resmi Thailand adalah?",
    pilihan: ["Peso", "Baht", "Ringgit", "Rupiah"],
    jawaban: "Baht",
  },
  {
    level: "Medium",
    soal: "Di mana letak Menara Eiffel?",
    pilihan: ["Italia", "Prancis", "Spanyol", "Jerman"],
    jawaban: "Prancis",
  },
  {
    level: "Medium",
    soal: "Dalam sistem kalender Masehi, bulan apa yang memiliki 28 atau 29 hari?",
    pilihan: ["Januari", "Maret", "Februari", "April"],
    jawaban: "Februari",
  },
  {
    level: "Medium",
    soal: "Apa yang digunakan lebah untuk membuat madu?",
    pilihan: ["Nektar", "Serbuk sari", "Getah pohon", "Embun"],
    jawaban: "Nektar",
  },
  {
    level: "Medium",
    soal: "Sungai terpanjang di dunia adalah?",
    pilihan: ["Sungai Nil", "Sungai Amazon", "Sungai Mississippi", "Sungai Yangtze"],
    jawaban: "Sungai Nil",
  },
  {
    level: "Medium",
    soal: "Alat musik tradisional dari Bali adalah?",
    pilihan: ["Angklung", "Gamelan", "Sasando", "Kolintang"],
    jawaban: "Gamelan",
  },
  {
    level: "Medium",
    soal: "Hewan mamalia yang bisa terbang adalah?",
    pilihan: ["Burung Hantu", "Kelelawar", "Elang", "Merpati"],
    jawaban: "Kelelawar",
  },
  {
    level: "Hard",
    soal: "Siapakah pelukis terkenal dari lukisan 'Mona Lisa'?",
    pilihan: ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
    jawaban: "Leonardo da Vinci",
  },
  {
    level: "Hard",
    soal: "Apa nama unsur dengan simbol Pb dalam tabel periodik?",
    pilihan: ["Timbal", "Platina", "Perak", "Kobalt"],
    jawaban: "Timbal",
  },
  {
    level: "Hard",
    soal: "Berapa jumlah tulang pada tubuh manusia dewasa?",
    pilihan: ["300", "206", "250", "150"],
    jawaban: "206",
  },
  {
    level: "Hard",
    soal: "Negara mana yang pertama kali menggunakan kertas?",
    pilihan: ["Yunani", "Mesir", "Cina", "Romawi"],
    jawaban: "Cina",
  },
  {
    level: "Hard",
    soal: "Planet terbesar di tata surya adalah?",
    pilihan: ["Jupiter", "Saturnus", "Uranus", "Neptunus"],
    jawaban: "Jupiter",
  },
  {
    level: "Hard",
    soal: "Siapa penulis teori relativitas?",
    pilihan: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"],
    jawaban: "Albert Einstein",
  },
  {
    level: "Hard",
    soal: "Negara mana yang memiliki populasi terbanyak di dunia?",
    pilihan: ["Amerika Serikat", "China", "India", "Indonesia"],
    jawaban: "China",
  },
  {
    level: "Hard",
    soal: "Apa nama planet yang memiliki cincin paling mencolok di tata surya?",
    pilihan: ["Jupiter", "Saturnus", "Uranus", "Neptunus"],
    jawaban: "Saturnus",
  },
  {
    level: "Hard",
    soal: "Berapa suhu titik didih air dalam skala Celsius?",
    pilihan: ["50°C", "100°C", "212°C", "0°C"],
    jawaban: "100°C",
  },
  {
    level: "Hard",
    soal: "Siapakah filsuf yang terkenal dengan pernyataan 'Aku berpikir, maka aku ada'?",
    pilihan: ["Aristoteles", "René Descartes", "Socrates", "Plato"],
    jawaban: "René Descartes",
  },
  {
    level: "Hard",
    soal: "Apa nama ibu kota pertama Indonesia sebelum Jakarta?",
    pilihan: ["Yogyakarta", "Bandung", "Surabaya", "Semarang"],
    jawaban: "Yogyakarta",
  },
  {
    level: "Hard",
    soal: "Unsur kimia paling ringan dalam tabel periodik adalah?",
    pilihan: ["Hidrogen", "Oksigen", "Helium", "Litium"],
    jawaban: "Hidrogen",
  },
  {
    level: "Hard",
    soal: "Siapakah presiden Amerika Serikat selama Perang Dunia II?",
    pilihan: ["Franklin D. Roosevelt", "Harry Truman", "Dwight D. Eisenhower", "John F. Kennedy"],
    jawaban: "Franklin D. Roosevelt",
  },
  {
    level: "Hard",
    soal: "Alat musik yang dimainkan dengan cara digesek adalah?",
    pilihan: ["Biola", "Gitar", "Piano", "Drum"],
    jawaban: "Biola",
  },
  {
    level: "Hard",
    soal: "Di negara mana Candi Borobudur berada?",
    pilihan: ["Thailand", "Kamboja", "Indonesia", "Vietnam"],
    jawaban: "Indonesia",
  },
  {
    level: "Hard",
    soal: "Apakah nama ilmiah untuk manusia?",
    pilihan: ["Homo erectus", "Homo sapiens", "Australopithecus", "Neanderthal"],
    jawaban: "Homo sapiens",
  },
  {
    level: "Hard",
    soal: "Pulau terbesar di dunia adalah?",
    pilihan: ["Greenland", "Australia", "Kalimantan", "Madagaskar"],
    jawaban: "Greenland",
  },
  {
    level: "Hard",
    soal: "Negara mana yang memiliki garis pantai terpanjang di dunia?",
    pilihan: ["Amerika Serikat", "Kanada", "Australia", "Indonesia"],
    jawaban: "Kanada",
  },
  {
    level: "Hard",
    soal: "Apa nama alat yang digunakan untuk mengukur kekuatan gempa bumi?",
    pilihan: ["Seismometer", "Barometer", "Anemometer", "Termometer"],
    jawaban: "Seismometer",
  },
  {
    level: "Hard",
    soal: "Dalam dunia biologi, 'DNA' merupakan singkatan dari?",
    pilihan: ["Deoxyribonucleic Acid", "Dinucleotide Amino Acid", "Double Nuclear Acid", "Deoxygenated Acid"],
    jawaban: "Deoxyribonucleic Acid",
  },
  {
    level: "Hard",
    soal: "Siapakah pendiri Microsoft?",
    pilihan: ["Steve Jobs", "Bill Gates", "Elon Musk", "Mark Zuckerberg"],
    jawaban: "Bill Gates",
  },
  {
    level: "Hard",
    soal: "Apa nama gunung berapi tertinggi di Indonesia?",
    pilihan: ["Gunung Kerinci", "Gunung Merapi", "Gunung Rinjani", "Gunung Semeru"],
    jawaban: "Gunung Kerinci",
  },
  {
    level: "Hard",
    soal: "Siapakah ilmuwan yang menemukan hukum gravitasi?",
    pilihan: ["Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Nikola Tesla"],
    jawaban: "Isaac Newton",
  },
  {
    level: "Hard",
    soal: "Siapakah penulis novel '1984' yang menggambarkan dunia distopia?",
    pilihan: ["Aldous Huxley", "George Orwell", "J.R.R. Tolkien", "F. Scott Fitzgerald"],
    jawaban: "George Orwell",
  },
  {
    level: "Hard",
    soal: "Apa nama teori yang menjelaskan asal mula alam semesta?",
    pilihan: ["Teori Relativitas", "Teori Big Bang", "Teori Evolusi", "Teori Kuantum"],
    jawaban: "Teori Big Bang",
  },
  {
    level: "Hard",
    soal: "Siapakah tokoh yang dikenal sebagai 'Bapak Komputer'?",
    pilihan: ["Alan Turing", "Charles Babbage", "John von Neumann", "Steve Wozniak"],
    jawaban: "Alan Turing",
  },
  {
    level: "Hard",
    soal: "Apa nama elemen terbanyak yang terdapat dalam kerak bumi?",
    pilihan: ["Oksigen", "Silikon", "Besi", "Aluminium"],
    jawaban: "Oksigen",
  },
  {
    level: "Hard",
    soal: "Apa nama negara yang memiliki bendera merah dengan satu bintang kuning besar dan empat bintang kecil?",
    pilihan: ["Vietnam", "China", "Korea Utara", "Jepang"],
    jawaban: "China",
  },
  {
    level: "Hard",
    soal: "Siapa ilmuwan yang pertama kali mengusulkan model heliosentris di mana Matahari adalah pusat tata surya?",
    pilihan: ["Galileo Galilei", "Nicolaus Copernicus", "Johannes Kepler", "Aristoteles"],
    jawaban: "Nicolaus Copernicus",
  },
  {
    level: "Hard",
    soal: "Hewan apakah yang memiliki jantung sebanyak tiga?",
    pilihan: ["Gurita", "Hiu", "Cumi-cumi", "Kuda Laut"],
    jawaban: "Gurita",
  },
];
